### ISSUE TITLE
require global is not present from within test file

### ISSUE THREAD

**Issue by mrt123** [noamtcohen/SlimJS#1]
adding : var process = require('child_process');  to the slim-fit-test.js.

Results in:
'ReferenceError: require is not defined'    outputted in the browser. However I have no problem accessing  some other node globals ... such as "process".  Is the intention of SlimJS to be able to run full node directly from test file?

**Comment by noamtcohen** [comment]
I've updated a fix and `require` should be available to test scripts

**Comment by mrt123** [comment]
Not sure if this is related, but after pull I get: 
Starting FitNesse on port: 8080
Output stream closed unexpectedly: Broken pipe (Stop button pressed?)

And the test reports: 
Could not complete testing: fitnesse.slim.SlimError: Error SLiM server died before a connection could be established. at Function.Module._load (module.js:301:12)

**Comment by noamtcohen** [comment]
Try to pull to a new directory and run `npm install`

**Comment by mrt123** [comment]
appears to work fine, tested with:
```
function Node(arument,num){

    this.exec = function(msg,cb){

        var exec = require('child_process').exec;
        exec('node -v',
                function (error, stdout, stderr) {
                    cb(null,"node version is: " + stdout);
                });
    };
}
```

and 
```
Test Node child_process
|script|Node |-v  |100             |
|check |exec |Hi  |node version is: v5.3.0 |
```

**Comment by noamtcohen** [comment]
cool. can I add your example to the project?

**Comment by mrt123** [comment]
sure go ahead
