### ISSUE TITLE
Debugging with node-debug

### ISSUE THREAD

**Issue by jbryson3** [noamtcohen/SlimJS#10]
We're running Fitnesse with SlimJS. I was wondering if there was an accepted way of putting debugger statements in the fixture code and debugging with something like node-debug.

Currently I'm peppering my fixture with console.log statements, running the test, then inspecting the output. It would really cut down on the feedback cycle if I could inject a proper debugger in there.

**Comment by noamtcohen** [comment]
After you run the test in FitNesse if you click "Test Executed OK" green button or red/orange in case the test failed, you should see stdio. Is this what you need?

**Comment by jbryson3** [comment]
That is good to view what happened as a result of the test run. However, I'm interested in attaching a full fledged debugger to my fixture code. Something along the lines of https://github.com/node-inspector/node-inspector

I've got a complex domain step that's failing. I could set up a bunch of console.log statements and view the output of running the test. But ideally i'd like to do something like this to be able to step through the code as it executes:

```
function SetupUser() {
  debugger;
  complicatedQuery1();
  complicatedQuery2();
  complicatedQuery3();
}
```

I've tried
```
!define COMMAND_PATTERN {node-debug --debug-brk=false SlimJS %p}
```
which theoretically should run the SlimJS process through the node-debug process so that I can pause execution of the steps and inspect the context of the JS. But so far this has been unsuccessful.

**Comment by noamtcohen** [comment]
That's very interesting.
I've never used node-debug, I'm trying to think why what you did didn't work...
FitNesse passes command line arguments to SlimJS, could be that node-debug is not propagating the arguments? 
Take a look at the entry point to better understand what I mean: https://github.com/noamtcohen/SlimJS/blob/master/src/SlimJS.js

**Comment by noamtcohen** [comment]
@jbryson3 where you able to get this to work?

**Comment by jbryson3** [comment]
I was able to get this to work. Not sure why it wasn't working for me the first time.

`!define COMMAND_PATTERN {node-debug --debug-brk=false SlimJS %p}`
