### ISSUE TITLE
Promises from Webdriver.IO are not fulfilled

### ISSUE THREAD

**Issue by NicoleRauch** [noamtcohen/SlimJS#15]
I am very glad that SlimJS handles asynchronicity gracefully by supporting Promises. But the promises that are returned from Webdriver.IO don't seem to be supported by SlimJS - they do not get resolved. As a demonstration, I have prepared this repo:

https://github.com/NicoleRauch/SpecByExampleAndPolymer

There you can see that in the fixture `CheckPageTitle` the `Title` method yields the correct result:

```
  this.Title = function () {
    return {
      then: function (fulfill) {
        _browser
          .url(_url)
          .getTitle().then(function (title) {
          fulfill(title);
        });
      }
    }
  };
```

whereas in the fixture `CheckPageTitleReturnDirect` the `Title` method does not get evaluated properly, instead an `[object Object]` is displayed in the table:

```
  this.Title = function () {
    return _browser.url(_url).getTitle();
  };
```

Looking at the code, it is not really clear where the difference comes from because in both cases there is a `then` function that can be evaluated by SlimJS. Just in the one case, it gets evaluated correctly, while in the other case, it doesn't.

Any ideas why this is the case, and how this can be fixed?

**Comment by NicoleRauch** [comment]
I had a closer look at the code and found the culprit:

in CallExecutor.js, in the function `isPromise`, you check for `Object.keys(obj).length ===1`. This check fails for the Webdriver.IO promises because they contain 24 (!) keys:

```
[ 'defer',
  'promise',
  'lastPromise',
  'desiredCapabilities',
  'requestHandler',
  'logger',
  'options',
  'commandList',
  'isMobile',
  'isIOS',
  'isAndroid',
  'next',
  'finally',
  'call',
  'then',
  'catch',
  'inspect',
  'unify',
  'addCommand',
  'getPrototype',
  'transferPromiseness',
  'depth',
  'name',
  'lastResult' ]
```

Why do you think it is important that the promise only contains exactly one key?

**Comment by noamtcohen** [comment]
You are right, it's not important, I removed the test of number of arguments. Could you please check?

**Comment by NicoleRauch** [comment]
Oh, sorry, I totally forgot about this one :-(
IIRC it did not work for some other reason, but the number of arguments can be removed anyways. Thanks! :-)
