### ISSUE TITLE
ScriptTable are run asynchronously

### ISSUE THREAD

**Issue by hlefebvr** [noamtcohen/SlimJS#20]
Hello there,

I'm just diving into fitnesse and SimJS so forgive me if I'm doing it wrong.

The ScriptTable table type implicitely implies that each rows of the table are run one after another. However, SlimJS does not seem to be waiting for asynchronous executions from the precedent line.

**Expected** : 
- I would have expected rows in ScriptTable to be executed one after another, waiting for the end of each promise in a row before processing the next. 

**What I experienced** :
- asynchronous rows are launched and the test executor is not waiting for rows to complete

**Example** : 
Suppose I have 
```
|Script:Some Example|
|loginInAnAsynchronousWay|
|check|logs|user logged in|
|logoutInAnAsynchronousWay|
|check|logs|user logged out|
```
Then it seems that checking logs is done before "loginInAnAsynchronousWay" as the promise has not finished yet.

Thanks for all guys !

**Comment by hlefebvr** [comment]
Anyway, for the moment, my work around is to simply do : 

```javascript
const rq = require('request-promise');

const waitFor = task => ({
  then: async (resolve, reject) => {
    try {
      const result = await task();
      resolve(result || true);
    } catch (err) {
      reject(err);
    }
  }
});

const AsyncTestDemo = () => {
  let response = 'unset';
  return {
     asyncFunction: () =>
       waitFor(async () => {
         response = await rq('http://perdu.com); // my async call
         return true;
     }),
    response: () => response
  };
};

module.exports = {
  AsyncTestDemo
};
```
which works like a charm.

However, isn't it deceiving that the following does not work ? : 
```javascript
const rq = require('request-promise');

const waitFor = task => ({
  then: async (resolve, reject) => {
    try {
      const result = await task();
      resolve(result || true);
    } catch (err) {
      reject(err);
    }
  }
});

const AsyncTestDemo = () => {
  let response = 'unset';
  return {
    asyncFunction: async () => {
      response = await rq('https://demoapi.moniki.io/operations_testBI/info');
      return true;
    },
    response: () => response
  };
};

module.exports = {
  AsyncTestDemo
};

```

**Comment by noamtcohen** [comment]
regarding the rows not being executed in sequence, I reviewed my code to make sure and it does execute in sequence also async functions I think the problem is in your code not with SlimJS.

regarding the example that doesn't work, I don't see where a ```then``` functions is returned?

And yes, the code will crash if the fulfill doesn't return a value when Fitnesse expects  one.

**Comment by hlefebvr** [comment]
Indeed rows are treated in order and I realised it after creating this issue. Forgive me about that :p 

Concerning the example that does not work, isn't a promise an object with a then method ? 

If you prefer and by memory, the following did not seem to work properly neither : 
`
const rq = require('request-promise');

const AsyncTestDemo = () => {
  let response = 'unset';
  return {
    asyncFunction: () => rq('http://perdu.com'),
    response: () => response
  };
};

module.exports = {
  AsyncTestDemo
};
`

**Comment by noamtcohen** [comment]
Should work. I'm not sure why it doesn't.
Are you using the version from git or npm?

**Comment by hlefebvr** [comment]
I guess I have the git version (I'm not the installer of our fitnesse config but I have dev folder and READMEs...)

I have just retested and here is a full example : 

### Test : 
```fitnesse
!define TEST_SYSTEM {slim}
!define COMMAND_PATTERN {node ../src/slimjs.js %p}
!path ../fixtures/examples

!contents -R2 -g -p -f -h

|import|
|async-issue|

|Script:example|
|call api|
|show|response|
|check not|response|/__VOID__/|
|show|responseLater|
```
### Fixture :

in the `async-issue.js` file
```javascript
const rq = require('request-promise');

const example = () => {
  let response;
  return {
    callApi() {
      return rq('https://jsonplaceholder.typicode.com/todos/1').then(res => {
        response = res;
      });
    },
    response() {
      return response;
    },
    responseLater() {
      return {
        then: resolve => {
          setTimeout(() => {
            resolve(response);
          }, 500);
        }
      };
    }
  };
};

module.exports = { example };

```

As you can see, response does return immediately the response from the API while the responseLater waits 500 ms before returning it (leaving enough time for the async request to be done). 

I get the following : 
![capture d ecran 2018-08-07 a 17 19 12](https://user-images.githubusercontent.com/25705781/43785250-30fd83fe-9a66-11e8-8871-40ad04efec41.png)

**Comment by noamtcohen** [comment]
What do you get?
What happens if you put ``` let response;``` in the top of the file (outside of ```example```)?

**Comment by hlefebvr** [comment]
If I move the `let response` outside the `example` class the result remains the same.

i.e. : 
- callApi is called asynchronously and is not waited for
- response is called before the asynchronous call is done, so the `response` variable is still set to `undefined`
- `responseLater` is called, this function waits for 500 ms before returning the same `response` variable which has now been updated by callApi which has finished in the meantime

**Comment by hlefebvr** [comment]
Well, yes otherwise the `responseLater` function would not have a defined value for response.

**Comment by hlefebvr** [comment]
See the screenshot, the `response` value is first `undefined` then turns to a JSON object which corresponds to the response of `GET https://jsonplaceholder.typicode.com/todos/1` [try here](https://jsonplaceholder.typicode.com/todos/1)

**Comment by noamtcohen** [comment]
What happens if you do this:
```javascript
callApi() {
   return {
          then:function(ful){
                rq('https://jsonplaceholder.typicode.com/todos/1').then(res => {
                    response = res;
                    ful(null);
                 });
          }
   }
```

**Comment by hlefebvr** [comment]
This would perfectly work, and that's why I don't understand why it does not work with promises. 

This is also why I'm currently using the following `waitFor` function I've written to use promises and async functions easier (see on the messages above) : 

```javascript
const waitFor = task => ({
  then: async (resolve, reject) => {
    try {
      const result = await task();
      resolve(result || true);
    } catch (err) {
      reject(err);
    }
  }
});
```

We are using this function to run all our tests actually.

**Comment by noamtcohen** [comment]
I'm sorry, I don't know why your example is not working seems liked it should.

**Comment by hlefebvr** [comment]
Have you been able to reproduce it ?

**Comment by noamtcohen** [comment]
This returns a promise right?
```javascript
return rq('https://jsonplaceholder.typicode.com/todos/1').then(res => {
        response = res;
      });
```
then ```then``` is called by slimjs and I think the promise is rejected and an exception is raised

**Comment by hlefebvr** [comment]
yes it returns a promise.

However, the promise does not raise any exception as `responseLater` returns a good response which corresponds to the response of the API.

To be sure though (but I truly have no doubt) I've also tried using : 

```javascript
callApi() {
      return rq('https://jsonplaceholder.typicode.com/todos/1').then(res => {
        response = res;
      }).catch((err) => {
        response = err
      })
    },
```
which resulted in the same way.

Really, you can test it with any promise if you don't trust `request-promise`. The same result occurs with the following : 
```javascript
new Promise(resolve => {
      const doItLater = () => {
            response = "new value"
            resolve(true)
      }
      setTimeout(doItLater, 250)
})
```

**Comment by hlefebvr** [comment]
If the promise is rejected then the .catch function would intercept it.

Note that it cannot be the case since `response` is updated afterwards.

As well, there are no Fitnesse exception raised except for the test checking that response is not /__VOID__/.
