### ISSUE TITLE
Chain With Instance Test

### ISSUE THREAD

**Issue by noamtcohen** [noamtcohen/SlimJS#3]
@ggramlich thanks a lot for your help,
I don't understand the functionality on this test:
[http://localhost:8080/FitNesse.SuiteAcceptanceTests.SuiteSlimTests.ChainWithInstanceTest?test](http://localhost:8080/FitNesse.SuiteAcceptanceTests.SuiteSlimTests.ChainWithInstanceTest?test)

What is the `SlimHelperLibrary` and `Slim StatementExecutor`

**Comment by ggramlich** [comment]
The StatementExecutor is the object that contains the methods which you implement in your instructions.js.
For this test, it is important that the StatementExecutor holds the current instance of the table actor

Java
https://github.com/unclebob/fitnesse/blob/master/src/fitnesse/slim/SlimHelperLibrary.java
https://github.com/unclebob/fitnesse/blob/master/src/fitnesse/slim/StatementExecutor.java

PHP
https://github.com/ggramlich/phpslim/blob/master/PhpSlim/PhpSlim/SlimHelperLibrary.php
https://github.com/ggramlich/phpslim/blob/master/PhpSlim/PhpSlim/StatementExecutor.php

**Comment by noamtcohen** [comment]
I don't understand at what instruction does the `SlimHelperLibrary` become the table actor?
Is that a good question? does it ever? maybe what I mean is when does the `call` instruction refer to the `SlimHelperLibrary`?
![test result](https://raw.githubusercontent.com/noamtcohen/SlimJS/master/img/ChainWithInstanceTest_1.png)

**Comment by chgans** [comment]
From http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.SlimProtocol
```
Call
[<id>, call,<instance>,<function>,<arg>...]

This instruction causes slim to find a function named <function> in the class of the object from the dictionary of created objects with the name <instance>. The function must have the same number of arguments as the instruction. If found, each argument in the instruction is converted to the appropriate type, and then the function is called on the instance. The <arg> strings may contain symbols (see below) which will be substituted before the type conversion is done. If the function returns a value, it is converted to a string and returned. Otherwise the instruction returns the string: /__VOID__/.

[0.1] System Under Test: Each fixture may have a way to declare a particular object to be the System Under Test. In java this is done with the @SystemUnderTest attribute. In RubySlim the object is accessed using the sut method. In .NET, the fixture implements the DomainAdapter interface. Whatever mechanism is used, if a the method specified by a Call or CallAndAssign is not found on the specified instance, then if there is a System Under Test object specified, and the method exists on that object, then it will be called.

[0.1] Library Instances: If a method specified by a Call or CallAndAssign is not found on either the specified instance, or on the System Under Test then the stack of library objects is searched, starting at the top (latest). If the method is found, it is called.

[0.3] Symbol As Object: If an <arg> consists entirely of a single symbol name prefixed with $, then the item from the dictionary of symbol values with the symbol name is used directly as an argument in the function call.
```
Along with 
```
Actors
[0.3] The stack of library objects should be initialized with an instance of a class with the following 3 methods:

    getFixture(): returns the object from the dictionary of created objects named "scriptTableActor". Throws an exception if no object exists.
    pushFixture(): pushes the object from the dictionary of created objects named "scriptTableActor" on to the stack of actor objects. Throws an exception if no object exists.
    popFixture(): pops an object from the stack of actor objects and adds it to the dictionary of created objects with the name "scriptTableActor". Throws an exception if the stack is empty.
```
My understanding is that by default, there's an instance of SlimHelperLibrary in the stack of library object, when you handlke a call to push/get/popFixture, and you cannot find it on any object, then you have to start looking at your stack of library object, which will always contains an instance of SlimHelperLibrary .

My 2 cents, Hope this helps.

**Comment by noamtcohen** [comment]
That's good information, I missed that part of the documentation. I will look into this.
Thanks!

**Comment by noamtcohen** [comment]
@ggramlich it seem that the documentation contradicts the php implementation as that the SlimHelperLibrary is add the the instance dictionary and not the library stack.
https://github.com/ggramlich/phpslim/blob/master/PhpSlim/PhpSlim/StatementExecutor.php#L25

I've rename `instructions.js

**Comment by ggramlich** [comment]
You are right.
The PHP implementation acutally introduced the push and pop feature.
After some discussion, it was added to the slim protocol and suggested to define it as the initial object on the stack library objects. But I did not change the PHP implementation to conform with the new protocol. My fault.

`StatementExecuter.js`should be `StatementExecutor.js`

**Comment by noamtcohen** [comment]
;)) thats funny.

**Comment by noamtcohen** [comment]
@ggramlich @chgans Thanks! Green! now I have to cleanup a little.

![test green](https://raw.githubusercontent.com/noamtcohen/SlimJS/master/img/ChainWithInstance_Green.png)
