### ISSUE TITLE
SlimJS 2.0.1 is very slow and throws an error

### ISSUE THREAD

**Issue by NicoleRauch** [noamtcohen/SlimJS#5]
I've upgraded to SlimJS 2.0.1 and found it to be extremely slow. This is what I tried:

I created a test page with a corresponding SetUp page. 
* If both pages are empty, this runs in no time.
* If I add a fixture import to the SetUp page, the (still empty) test page takes between 36 and 55 seconds to run! During that time, there is lots of searching going on on the hard drive.
* When i remove all search paths except the one I need to load, there is no audible hard drive searching going on any more, but the page still takes 36 to 55 seconds to run.

I hope you can imagine that with this timing, it is impossible for me to use it. I'm using FitNesse to work in a Specification by Example fashion, and my pages are mostly at the granularity of unit tests - I need fast feedback on these...

Interestingly, this gets written to standard error when I run the page:

.../node_modules/slimjs/src/SlimJS.js:43
        var command = instructionArguments[1];
                                          ^

TypeError: Cannot read property '1' of undefined
    at executeInstruction (.../node_modules/slimjs/src/SlimJS.js:43:43)
    at onReceivedInstructionSet (.../node_modules/slimjs/src/SlimJS.js:24:9)
    at executeInstructionSet (.../node_modules/slimjs/src/tcp/ConnectionHandler.js:58:9)
    at tryToParsePayloadBody (.../node_modules/slimjs/src/tcp/ConnectionHandler.js:48:13)
    at Socket.processData (.../node_modules/slimjs/src/tcp/ConnectionHandler.js:25:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

**Comment by noamtcohen** [comment]
I understand your problem and that it makes the system unusable.
I haven't encountered this error on the project I'm working on and it's hard for me to understand from the log and your description what is wrong.
Can you create a repo with this minimal case that I can checkout?

**Comment by NicoleRauch** [comment]
The test passes and is green. If you then click on the green "Tests Executed OK" button, you see the error I mentioned above.

I've started to set up a minimal workspace to reproduce the slowness. But, like you, I don't run into this issue if it is very minimal. So I need to keep expanding this in order to get to the problem. This might take me a while.

OTOH, I *can* see the error I mentioned above in my minimal version, so if you don't see it, please get back to me and I can give you this minimal version.

**Comment by noamtcohen** [comment]
Yes, please.

**Comment by NicoleRauch** [comment]
This is a minimal setup: https://github.com/NicoleRauch/slimjs-experiments

Just run npm install and then launch fitnesse via java -jar fitnesse-standalone.jar

On the main page, there is one test case - if you run it and then click on the green button, you should see the above error message.

I'll try to extend this example to demonstrate the slowness as well, but this will take me a couple of days I'm afraid.

**Comment by noamtcohen** [comment]
The error is due to me ignoring the "bye" message from FitNesse and is not related to you problem. anyway I fixed this and publish to npm `2.0.2`.
I think the issue you have is an infinite recursion setup in FitNesse:

`FrontPage.SetUp` is including page `FrontPage.SetUp` which is including page `FrontPage.SetUp`  ...

**Comment by ilyagutman** [comment]
Hello Noam, I had exactly the same problem with the "bye" message in 2.0.1 and even added the explicit error message in the executeInstruction() method, to explicitly show in the test log that this error is benign and is due to the handling of the "bye" message on exit. I did upgrade to 2.0.2 and the error message disappeared. Thank you.

However, I started to experience a problem that I didn't experience with 2.0.1 - each test now runs exactly the duration of the timeout. Before the upgrade each test took a fraction of a second. Now they all run for 10 seconds (or whatever the slim.timeout setting I use), unless I run it as a suite. Would you have an idea of what I am potentially missing?

Thank you
Ilya Gutman

**Comment by noamtcohen** [comment]
I think I understand the problem and it has to do maybe with the fact that the SlimJS node process is not killing after the bye message. What happened before was the the un caught "bye" message was killing the process. I'm not sure about this but will take a look later.

**Comment by noamtcohen** [comment]
I released a minor version 2.0.3. Please updated. 
The problem was that the `bye` message was not exiting the node process. Please let me know if this fixes your issue. Thanks.

**Comment by ilyagutman** [comment]
Yes Noam, the 2.0.3 did solve the problem. Tests are back to the sub-second execution time. Thank you for the instant turn around.

**Comment by noamtcohen** [comment]
@NicoleRauch does this work for you too?

**Comment by noamtcohen** [comment]
@NicoleRauch can I close this issue?

**Comment by NicoleRauch** [comment]
Yes, please close it. I need to investigate this more thoroughly and am currently busy with other stuff. Will open another ticket as soon as I know more. Thanks!

**Comment by noamtcohen** [comment]
Thank you, these issues you raised had a significant impact on the project.

**Comment by NicoleRauch** [comment]
Just to let you know: It seems that this speed problem is somehow related to my machine - my colleague does not experience it. Strange.

**Comment by noamtcohen** [comment]
When I was looking at the repo you sent me It seemed you have some kind of recursion in the FitNesse setup. The page you where testing was including itself. Are you aware of the special named pages in FitNesse? http://www.fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.SpecialPages

**Comment by NicoleRauch** [comment]
Yes, I am aware of the special pages (I guess you are referring  to SetUp in particular here). But what do you mean by "recursive setup"? SetUp is a brother of the test page and therefore it gets included. That is the way FitNesse handles the SetUp page to my understanding.

**Comment by noamtcohen** [comment]
When I downloaded the repo a few weeks ago,  I saw something strange that I don't see now...
It looked like a page was including itself which cause the test to run in a loop and that explained the excessive IO  you reported. But I don't see this anymore...

**Comment by NicoleRauch** [comment]
I did not see this. Maybe the link to the SetUp page looked confusing?

**Comment by noamtcohen** [comment]
Probably. Voodoo.
