### ISSUE TITLE
Running SlimJS test suite in CI?

### ISSUE THREAD

**Issue by NicoleRauch** [noamtcohen/SlimJS#7]
I am currently using FitNesse + Slim to test the backend part of an application, and now I would like to use FitNesse + SlimJS to test the frontend (JavaScript) part as well. I would especially like to run the tests in CI, i.e. without running FitNesse in the browser. For the backend tests, I'm using the FitNesseRunner:
```
@RunWith(classOf[FitNesseRunner])
@Suite("Rankings")
@FitnesseDir("rankings")
@OutputDir("rankings/target/test-reports")
class RunRankingsViaJUnitTest {
  // no code, just triggers junit to run FitNesse suite
}
```
This can be run via JUnit, together with all other tests.

For the SlimJS tests, this mechanism does not work because the FitNesseRunner tries to find the fixtures among the Java classes, and of course they are not there because they are written in JavaScript.

Do you know of any mechanism to integrate the SlimJS test into a CI build, or do you plan to provide something along these lines?

**Comment by noamtcohen** [comment]
I'll tell you what I'm setting up now, Basically I'm running the FitNesse jar on the CI server and doing a `curl` (localhost from the CI) to my test page in FitNesse, Then I can parse the output with a [plugin](https://wiki.jenkins-ci.org/display/JENKINS/FitNesse+Plugin).
You can append `&format=xml` to the url in FitNesse and you could write your own test result parser so you don't have to use Jenkins.

**Comment by NicoleRauch** [comment]
That's what I looked into as well. I'm not that fond of it because it implies managing the firing up of the server and the shutting it down, but if this is the only way, then that's feasible. Will the Jenkins plugin take care of the missing CSS?

**Comment by noamtcohen** [comment]
missing CSS?

**Comment by NicoleRauch** [comment]
I would like to be able to see the test results as they were produced by Jenkins. When I curl the test page, I get these results, but they don't look nice, because the CSS is missing (tables are not coloured in red & green etc.). When I run my backend FitNesse tests with the JUnitRunner, it creates HTML output and additionally provides the required CSS files, images etc. and places them next to the HTML output. For the curled result, this is not as easy because these CSS files etc. are kept within the fitnesse.jar file (they are not dumped out to the cmdline like the FitNesse wiki contents). Therefore, it is not easy to get nicely looking test results.

**Comment by noamtcohen** [comment]
I understand. I don't plan on developing a plugin right now, maybe you could help?
did you look at the previous link?
http://fitnesse.org/FitNesse.UserGuide.AdministeringFitNesse.ControllingFitNesseFromTheCommandLine

You can run a test from the command line like this:
```bash
java -jar fitnesse-standalone.jar -c "MyTestPage?test&format=text"
```

The text format causes a simple summary of the tests to be printed to standard output. It looks like this:
```bash
Starting Test System: slim using fitnesse.slim.SlimService.
. 07:37:29 R:0    W:0    I:0    E:0    JunkPage (JunkPage) 0.124 seconds
X 07:37:29 R:0    W:0    I:0    E:3    ExceptionTest    (JunkPage.ExceptionTest) 0.034 seconds
. 07:37:29 R:0    W:0    I:0    E:0    FirstPage        (JunkPage.FirstPage) 0.329 seconds
. 07:37:29 R:2    W:0    I:0    E:0    GivWenZen        (JunkPage.GivWenZen) 0.528 seconds
F 07:37:30 R:6    W:1    I:0    E:0    HashTablePage    (JunkPage.HashTablePage) 0.045 seconds
F 07:37:30 R:1    W:20   I:0    E:8    CanTotalOrder    (JunkPage.ImportingPage.CanTotalOrder) 0.623 seconds
X 07:37:30 R:0    W:0    I:0    E:6    JunkPage (JunkPage.JunkPage) 0.083 seconds
. 07:37:30 R:0    W:0    I:0    E:0    JunkTest (JunkPage.JunkTest) 0.884 seconds
F 07:37:30 R:1    W:20   I:0    E:8    CanTotalOrder    (JunkPage.PointOfSale.CanTotalOrder) 0.004 seconds
. 07:37:30 R:0    W:0    I:0    E:0    SeeTest  (JunkPage.SeeTest) 0.765 seconds
. 07:37:31 R:1    W:0    I:0    E:0    SymbolPage       (JunkPage.SymbolPage) 0.198 seconds
. 07:37:31 R:0    W:0    I:0    E:0    TestNothing      (JunkPage.TestNothing) 0.923 seconds
X 07:37:31 R:2    W:0    I:0    E:2    TestTableTable   (JunkPage.TestTableTable) 1.120 seconds
X 07:37:31 R:0    W:0    I:0    E:4    UseVarPage       (JunkPage.UseVarPage) 0.034 seconds
. 07:37:31 R:0    W:0    I:0    E:0    VariableTest     (JunkPage.VariableTest) 0.512 seconds
. 07:37:31 R:0    W:0    I:0    E:0    SuiteSetUp       (JunkPage.ParentSuite.SuiteChildTwo.SuiteSetUp) 0.321 seconds
. 07:37:31 R:0    W:0    I:0    E:0    TestPage (JunkPage.ParentSuite.SuiteChildTwo.TestPage) 0.432 seconds
. 07:37:31 R:0    W:0    I:0    E:0    SuiteTearDown    (JunkPage.ParentSuite.SuiteChildTwo.SuiteTearDown) 0.387 seconds
. 07:37:31 R:0    W:0    I:0    E:0    SuiteSetUp       (JunkPage.ParentSuite.SuiteSetUp) 0.712 seconds
. 07:37:31 R:0    W:0    I:0    E:0    TestPage (JunkPage.ParentSuite.TestPage) 0.209 seconds
. 07:37:31 R:0    W:0    I:0    E:0    SuiteTearDown    (JunkPage.ParentSuite.SuiteTearDown) 0.314 seconds
. 07:37:31 R:0    W:0    I:0    E:0    SuiteSetUp       (JunkPage.ParentSuite.SuiteChildOne.SuiteSetUp) 0.159 seconds
. 07:37:32 R:0    W:0    I:0    E:0    TestPage (JunkPage.ParentSuite.SuiteChildOne.TestPage) 0.265 seconds
. 07:37:32 R:0    W:0    I:0    E:0    SuiteTearDown    (JunkPage.ParentSuite.SuiteChildOne.SuiteTearDown) 0.358 seconds
--------
24 Tests,       7 Failures.      90.409 seconds.
```
