### ISSUE TITLE
When a function is missing in a fixture, the error message is very, very hard to understand

### ISSUE THREAD

**Issue by NicoleRauch** [noamtcohen/SlimJS#8]
It basically says "Could not complete testing: java.lang.ArrayIndexOutOfBoundsException: 2"

I would rather prefer it to show me which function I should implement (I usually use this feature to test-drive my fixture code).

See example here: https://github.com/NicoleRauch/slimjs-experiments with test page http://localhost:9999/FrontPage.ArrayIndexOutOfBoundsException

**Comment by noamtcohen** [comment]
I published a fix v2.1.2. I didn't implement the exception handling properly and was missing the class name:
http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.SlimProtocol

see: `NO_METHOD_IN_CLASS` exception.

**Comment by NicoleRauch** [comment]
Works great, thanks!
