### ISSUE TITLE
"set" methods do not pass on all text that is given to them

### ISSUE THREAD

**Issue by NicoleRauch** [noamtcohen/SlimJS#9]
I noticed that if I pass a number with a trailing percent sign to a "set" method of a fixture, the fixture only receives the number, not the percent sign. I've added a demonstration page to my repo:

https://github.com/NicoleRauch/slimjs-experiments

The page is called PercentSignIsSwallowed.

**Comment by noamtcohen** [comment]
Please update v2.1.3
